### ISSUE TITLE
Chapter 4, PluginProcessor.cpp, change MIDI to Midi

### ISSUE THREAD

**Issue by tomaszrykala** [hollance/synth-plugin-book#5]
Hi, as per coding standards, abbreviations shouldn't be TITLECASE, therefore shouldn't the method `handleMIDI(...)`, be
`void handleMidi(...)` ? - Chapter 4, page. 81.

The juce library also has MIDI written as `Midi` in its classes, fields and methods.

**Comment by hollance** [comment]
Coding standards are largely a matter of opinion, and my opinion is that it's fine to write MIDI instead of Midi. 😄 But feel free to change the name to `handleMidi()` if you like that better!

**Comment by tomaszrykala** [comment]
Thanks for the reply.
